name: flutter_bilibili
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  json_annotation: ^4.5.0
  shared_preferences: ^2.0.15
  fluttertoast: ^8.0.9
  underline_indicator: ^0.0.4
  flutter_swiper_null_safety: ^1.0.2
  flutter_staggered_grid_view: ^0.4.0
  transparent_image: ^2.0.0
  cached_network_image: ^3.0.0
  lottie: ^1.0.1
  chewie: ^1.2.2
  video_player: ^2.1.6
  orientation: ^1.3.0
 
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.1.10
  json_serializable: ^6.2.0
  json_model: ^1.0.0

flutter:
  uses-material-design: true
  assets:
      - res/image/
      - res/animation/